version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: tic_tac_toe_db
      POSTGRES_USER: tic_tac_toe_user
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["gunicorn", "tic_tac_toe_images.wsgi:application", "--bind", "0.0.0.0:8001"]
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
