# Generated by Django 5.0.7 on 2024-09-01 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='shared_link',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
