# Generated by Django 5.0.7 on 2024-10-16 12:29

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_shared_link_sharedgame_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
